export const releaseNotesData = {
  R70: [
    {
      title: "Manufacturing Flow Updates",
      items: ["Factory Outward Page: Manufacturing process more speedy in factory outward.", "Casting Process: In casting there will be option of dynamic transaction issue return department.", "Order Type: Order Type display in transaction, engage material pages."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Reconcile: Stock Reconcile mismatch print provided and excel export in.", "Product cost analysis: From now onwards for  job work metal rate will fetch 0 in purchase cost and mrp.", "Job import: Outsource job import will be now available too"],
    },
    {
      title: "E-Commerce Updates",
      items: ["EComm-WebSites: Razor pay integration available now."],
    },
    {
      title: "Common Updates",
      items: ["Import MRP: From now onwards you can add import through import process too.", "Excel export: Stock book and sale report add  lineid and batch no in it.", "Daily statement: Added subhead and event name in it."],
    },
    {
      title: "Special Updates",
      items: ["Loss Report Excel: Excel of data for FG outward department wise and total loss in it including issue and return in it.", "Quotation: From now onwards you can add multi labor in quotation for special findings.", "Policy master: You can add weight range through Exclude Finding from it.", "Icatalogue: calculation updates for multi labour applied in it.", "job print: you can print material wise bag print in it."],
    },
  ],
  R69: [
    {
      title: "Manufacturing Flow Updates",
      items: ["WIP Report: If age 0-2 hours then it will show in blue color and Excel export including PO number and Line number in it."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Stock Book: Multiselection and priority colors have been added, similar to the sales jobs page.", "Set MRP: You can now update the MRP in terms of amount itself.", "Due Date Report: Added sales rep. in it."],
    },
    {
      title: "Common Updates",
      items: [
        "Memo from Manufacturer: The job cannot be returned to manufacturing flow if it was only purchased by memo.",
        "Design Collection: In image view hyperlink of designno to design master view.",
        "Quick Add designs: Added job count in it.",
        "Word senstitive: From now onwards in reports fields such as design no, voucher no. will work with like search in it.",
        "Merge jobs: You can add more than three jobs in it.",
        "Jewellery book: Added Opening stock filter in it and Added date filter according to purchase date wise too.",
        "Employee: Added department and location filter in it.",
        "Stock Book: You can view last location too while factory return single job wise.",
        "Multi Metal in ledger and sale report: You may view various metal types according to event in the ledger and in the sale report as well.",
        "Order changes: The quantity checkbox will now be off by default going forward.",
      ],
    },
    {
      title: "Special Updates",
      items: ["QA Book: Provided QA pending status in it and when it moves to stock book will show aging accordingly", "PRO QC: Option of QC for production and sales in Tablet view."],
    },
  ],
  R68: [
    {
      title: "Manufacturing Flow Updates",
      items: ["MFG Location Selection Option: From now onwards while returning job to production, you need to select location.", "WIP Report: Added delivery batch in excel export.", "Finding Creation: Added logs for finding bags created along with criteria in grid itself.", "Engage Report: New report for logs for users who has engaged job init. History of last three months will be visible in it.", "Metal loss Summmary: Added pure wt column for return job.", "Transaction: Transaction Will show wax diamonds diffrenet in it.", "Melt updates: Refinery job melting entries will appear in the melt department, where loss will be computed."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Jewellery Book: Job reference number was added to the Excel export.", "Material Wise Reports: Added pure weight and finding details in it.", "Quick Search: Added history of splitted jobs from main job in it.", "Sale Return: From now onwards in sale return finding entries will show differently in it.", "Scan Job: Added two buttons in memo return and sale return.", "Closing Balance:Closing balance will show last paid date in it in customer."],
    },
    {
      title: "Common Updates",
      items: ["Material Purchase: Price fetch auto in material purchase from price policy for diamond, colorstone and misc.", "Jobs: If design master have multimetal then multimetal flag will get auto fetch in it."],
    },
  ],
  R67: [
    {
      title: "Manufacturing Flow Updates",
      items: ["Procuremnt Report: WIP Report will get splitted into two parts  - Pending Rquest , bagging in it and other status in WIP . Also procurement will show pending material status too in it. A specific report has been added for the process, which shows pending jobs whose material is still pending and will stay different in this report until it is changed to work-in-progress.", "Engage Flow: Material will now be engaged at all times, regardless of whether the work is in issue or receive state. Report on procurement.", "Employee issue: A return link has been added, which can be accessed right here. The employee's return weight will be added to the metal rfbag."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["BULK PURCHANGE PENDING: introduced a new page from which you can access the vendor-free tagging page.", "Material wise sale and stock report: Added vendor in it . Also added search option of filters such as color and size .", "Item master: The New HSN master is dynamic and and generated right here.", "Certificate import: Inserted a stamping column to retrive values in jobs where stamping is applied via import."],
    },
    {
      title: "Common Updates",
      items: ["Discard finding color: Color will now be bound by metal color instead of using a separate master to finding master color."],
    },
    {
      title: "Special Updates",
      items: ["Retail Bill Updates: 1. The choice to apply taxes to invoices other than cgst+sgst and igst.   2. Added Go button in it to run it smoothly in tablet view.  3. Option of auto priviledge card in it and SMS facility for security purpose.", "Saving Scheme Updates: Cash date and reference number were added.", "Retail Order : Data will automatically replicate and establish a new order in it if an existing design number or work number is added."],
    },
  ],
  R66: null,
  R65: [
    {
      title: "Manufacturing Flow Updates",
      items: ["Loss Recover: From now if job return to production and want to recover loss through transaction(MFG) page, it will not allow to recover FG outward loss from transaction page.  It will only allow to recover current Production loss from transaction(MFG) page.", "Return to Fatory: Have updated the technology to streamline the factory return and factory outward stock book processes.", "Speed Tasks: It operates faster in it when items are deleted and restored from bill.", "Recast Jobs: You may now dynamically add tags and reasons through masters and generate an Excel output as of now.", "Procurement Report: WIP Report will lget splitted into two parts - Pending Rquest, bagging in it and other status in WIP. Also procurement will show pending material status too."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["FG Stock Summary: You may now view date search stock for jewelry on ZForm.", "Repairing Report New: Columns for metal loss and pure weight were added."],
    },
    {
      title: "Common Updates",
      items: ["Material Wise Stock Report: This report can be viewed, along with the job number.", "Issue Material: Notes can be added to it and modified as needed.", "Repair Bill: Reparing flow has been adjusted, and as of right now, a different effect will also be shown in the ledger.", "Memo to Sale for Customer Memo : Memo amounts in bills will always be carried over into billing.", "Quote Updates : updated adjustments in bulk for the added size and quantity options. Additionally, bulk finidngs can be assigned and removed from it."],
    },
    {
      title: "Special Updates",
      items: ["Type in Diamond, ColorStone and Misc : Have included a type in the content to define it with different HSN and TAX and give information about it throughout the entire flow."],
    },
  ],
  R64: [
    {
      title: "Manufacturing Flow Updates",
      items: [
        "Recast jobs: When recasting jobs from the job book, instructions have been added, and the recast jobs report will display these instructions as well.",
        "Scan job: Here, an estimate option has been added, making it possible to include RFID events in some situations.",
        "RM Reconcile: The customer name will now appear in the RM reconciliation for diamonds and colorstones.",
        "Employee wise Metal: The report will display the same as it does for filing for other departments, precisely like the issue weight terminal.",
        "Search job: Search jobs will now include indicate the finding engage weight.",
        "Wax Engage Material: Wax Engage material also allows you to print stickers.",
        "Finding Creation: Now you can scan finding bags to create findings from another findings.",
        "Transaction: Suppliers will now be included in the summary grid.",
        "Dust Collector: It now has the option of ignoring employees.",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: [
        "Design Collection: All filters are currently derived from the master. They will now be bound from the design master, which will include binding for categories, subcategories, and collections.",
        "Stock View in Stock Reconcile: You can print out the details of products not found from this location, ensuring that the print format matches the one in the jewelry book.",
        "StyleBank Import: You can now import finding details, including settings, in it going forward.",
        "Customer Return: Added pcs option in it.",
        "Added verified flag in following pages: General purchase, General Sale, and General Sale Return.",
        "Stock Purchase: If the setting type is added to the order, it will be autofetched in the purchase from order.",
        "Scan job: We have added a status for differentiating data in the stock book based on whether it is third-party pending or verified.",
        "Capital Report: Additional gold report that details the event-by-event breakdown, including sales events too.",
        "Quote: Its display order has been updated. Dispatched in it first.",
        "Retail Bill: It now has a privilege card system.",
        "Franchisee Updates: Update the franchisee and branch systems to transfer items from the head office to the branch/franchisee system.",
        "Repair Print: If a job reference number is available, you will see it in print from now on.",
        "Product Alteration: A new repair print format has been added to it.",
      ],
    },
    {
      title: "Common Updates",
      items: ["Help: You can access help for various features by clicking the 'i' icon on each page. For example, Product alteration, split transfer, advance pricing policy, material sale, etc."],
    },
    {
      title: "Special Updates",
      items: ["iCatalog: You can accept offline exhibition and travel orders with the help of iCatalog.", "Jadau Process Flow: The Jadau production process involves splitting a single job based on the requested ETA, according to the specific type of Jadau, streamlining the production workflow."],
    },
  ],
  R63: [
    {
      title: "Manufacturing Flow Updates",
      items: ["FG Outward: From now onwards FG outward will be possible only if the employee has its sales location rights else not. Brand filter added in advance filter of FG detail report.", "Finding Conversion: Currently if metal bag issued in finding conversion then bag gets locked and cannot be used in stock transfer, From now onwards you can use it.", "WIP Report Print: From now, The WIP report print will be show item list according to the promise date (the one nearest to the promise date will appear first)."],
    },
    {
      title: "Common Updates",
      items: ["Design Master: Default size added will show in grid list and design master view.", "Customer: Common action button in customer for operating multiple customer actions such as activation, price policy, customer type through a single click.", "Online Designs: Option of get back in online designs in ready to move.", "HUID and Certification: Currently if HUID not added then stamping details not getting saved. From now onwards it will get saved with default pcs as 1 in it.", "User rights: From now onwards employee too will have rights for user permission tab according to rights based."],
    },
    {
      title: "Special Updates",
      items: ["Sales QC process: You will be able to view Order weight too in it.", "GSTR Report: Have made proper details in GSTR Report according to government norms and rules.", "Stylebank import and export: Can validate excel import for not creating any new masters in it and Its setting based on our side.", "Due Date Report: Have updated bill settlement module. From now onwards you can view due date according to settlement too.", "Concept: Added brand in concept PD Order and jobs - We have added brand filter in PD order and jobs page."],
    },
  ],
  R62: [
    {
      title: "Manufacturing Flow Updates",
      items: [
        "WIP Report: From now onwards there will be no specialized color in WIP for delivery planning jobs instead of that we have Displayed Delivery date in WIP report and stock book too.",
        "Factory Outward: From now onwards Factory outward will be done according to user's stock location rights (if only one location rights given to him) and employee have multiple location rights then it will be factory outward to default stock location.",
        "Metal Conversion: Formula is updated. Now Loss will be deducted from destination RF bag instead of Source Bag. Demanded tab will get removed from this update.",
        "Transaction: Removed date from transaction. Applied same updates in Wax Engage material, Wax engage and batch transaction.",
        "Factory Bulk Split: From now onwards you can split bulk jobs in manufacturing too.",
      ],
    },
    {
      title: "Wholesale & Retail Flow Updates",
      items: ["Handling Charges: If company diamonds then also you can apply handling charges in it from billing. If diamond is of vendor then no handling will get applied in it while purchase.", "Irys RFID integration: Technical Updates in it as for making process fast and easy in it."],
    },
    {
      title: "Common Updates",
      items: [
        "Material History: You can view UserID and invoice vendor name in Material History.",
        "Icatalogue Updates: From now onwards designs in Icatalogue will be viewed through Icatalog package in Customer Type.",
        "Procatalog: You can use Procatalog option for Album. Through this link your customer can order directly.",
        "Stock Book: Production completed job's age will display in stock book.",
        "Logs: From now log of style bank import will be shown in transaction log with user id.",
        "OTP changes: From now onwards OTP will be sent to employee's mobile number for roaming access. If employee has no access then they can take OTP from Admin too using Employee OTP page.",
        "Due Date Report: All current due date reports will get discarded and new report is introduced in this update. In that report all relevant data will be shown and this report will be combined report of all due date reports.",
        "Notification: From this update you will get help in page features itself such as currently added in Wastage Price, Material Sale, Product Alteration pages. Future progress will be there for other pages too in the next update.",
      ],
    },
    {
      title: "Special Updates",
      items: ["Order Info: Now you can view PO number, line number, and batch number in this report and can do excel export.", "Memo IGI Excel: Have added two extra columns in it Design no and job no. Also displayed gross weight and diamond weight in two decimals.", "Easy Pages: Added following two pages for simplification of flow - Mfg Easy page and Accounts Easy page."],
    },
  ],
  R61: [
    {
      title: "Manufacturing Flow Updates",
      items: ["Mount and Finding Scrap Return : From now onwards you can directly convert finding and mount scrap to metal from transaction page.", "Dust Collector Report : Added Date filter in it.", "FG Detail Date Wise New   : We have added Category in  it.", "WIP Report  : Added delay hours in it for current department along with sorting    You can  add planing date  for Multiple jobs too.", "WIP Reconcile : From now onwards pending request jobs too will get scanned in it."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["MRP Updates :  If job added in MRP and added discount in it in memo then in billing by default same Price will fetch in it.", "Stock Purchase Import :  From now onwards Memo Purchase import will work too.", "Lock Validation :  From now onwards if E-invoice created then such invoices will get lcoked. For special permission you can unlock it from Admin."],
    },
    {
      title: "Common Updates",
      items: [
        "Material History  :",
        "Express APP  : Customer Limit extended upto 50 in it.",
        "Discount Updates in Memo  : Now you can apply discount in memo single job wise too.",
        "Return Material  : Have made Return material page more speedy.",
        "Jewellery Book:UI updates and you can make Album from Jewellery Book too.",
        "HUID and Certification Updates  : Currently if huid and certification number added and then got returned to production then huid and certification services (misc details) gets removed from now onwards it will remain there even if job gets returned to production .",
        "Account Head  : We have added  Suspense Account in it.",
        "Import  :",
        "Excel Export     : Export Sale bill from here and import as stock purchase in same format.",
        "Import : Now you can import job wise cetification number too.",
        "Metal Loss Summary  : Update formula for diffrence and labellings in it.",
        "Multi Labour  : Now you can add multi labour in billing for diffrent findings.",
        "Stock Summary  : Added Pure weight Column in  it.",
        "Memo Report  :  We have added Jobs Customer information too.",
      ],
    },
    {
      title: "Special Updates",
      items: ["NOTE  :Topics are Reflect to your account only its relevant to your Account.", "Icatalogue : You can now add company type wise price master."],
    },
  ],
  R60: [
    {
      title: "Manufacturing Flow Updates",
      items: ["Split Job in Factory : From now, it is possible to split the metal weight from main job into two separate jobs, each of which will be processed differently for the further manufacturing process.", "RM Stock  : Added Group For production status so that you can get multiple department wise production status in RM stock .", "Conversion  : Purity Conversion will now work perfectly if you have more than one pure metal."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Customer Registration :Customers who create  using Customer Registration their mobile numbers will be automatically verified."],
    },
    {
      title: "Common Updates",
      items: ["Employee Excel Export : Added some fields such as emergency contact person, emergency contact number.", "Salary Report : In the Salary Report, add a column for gms and pcs.", "Item Wise Audit Report : Included tax amount for sale event in this report.", "Design Collection : We have added a Gender filter to the advance search.", "Excel Export : Kalyan Export for Billing was added.", "Multicurrency : From now you can add labour and delivery charges in labor set and wastage price according to the currencies.", "Line id import : : Using the line id import feature, you can import line id through excel according to order."],
    },
    {
      title: "Special Updates",
      items: ["NOTE  :Topics are Reflect to your account only its relevant to your Account.", "Icatalogue : You can now add company type wise price master."],
    },
  ],
  R59: [
    {
      title: "Manufacturing Flow Updates",
      items: ["Bulk Flow in Manufacturing : Now you can use single job flow for multiple\n                                    items and split in sales.", "Worker Without Finding summary : Added recalculate button for data refreshed.", "Order Status Report : You can see  the job  running status according to SKU in order status report.", "WIP Reconcile Report : Such jobs will no longer be counted in WIP when their weight is 0."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Received Repair : Finding weight will now be taken into received repair jobs."],
    },
    {
      title: "Common Updates",
      items: [
        "Other Charges Report : You can also view handling charges in this report .",
        "Bill Settlement Updates : Previously once settled entry deleted, its\n                                        effect not coming in cash voucher, Now onwards you can edit cash voucher.",
        "Customer : Added filter for Active and Deactive customer.",
        "Quote/Memo : From this point forward, if a fixed amount is applied, it will do so for all quantities as well as the choice of on pcs, in which case labour will be applied pcs-wise.",
        "Auto Hallmark, Stamping and Certification Charges : Now you can add\n                                        hallmark, Stamping and certification auto from HUID and certification\n                                        itself.",
        "Quote : You can use the same 24k metal rate for customization that is currently being used in billing.",
        "Material History : From now onwards if lost data updated in transaction\n                                        page, its effect will be considered in material history too.",
        "Multi Currency in billing : Discounts will now be manually added, currency-wise, ( only for pc wise concept and on total amount )",
        "Small Label Changes : As we are applying Auto charges for other and misc\n                                        through colorstone master we have updated label as ColorStone/MISC/ Services .",
      ],
    },
    {
      title: "Special Updates",
      items: ["Payroll Update \n                                         1.Now admin will play role in salary report too."],
    },
  ],
  R58: [
    {
      title: "Manufacturing Flow Updates",
      items: [
        "Metal conversion :  We are updating the conversion formula for lower purity to higher purity\n              (e.g. 14K --> 18K) as per below\n              \n              Current Formula :\n              \n              1000gm Gold 14K (58.00 Purity) convert to Gold 18K (75.00 Purity)\n              \n              Converted gms = (1000*58) / 75 = 773.333\n              \n\n              Upcoming Formula :\n              \n              1000gm Gold 14K (58.00 Purity) convert to Gold 18K (75.00 Purity)\n              \n              Require 24k gold to be added = ((75-58)*1000) / (99.99-58.00) = 404.858\n              \n              Converted gms = 1000gms + 404.858 = 1404.858",
        "Wip Reconcile Report : Generated WIP Reconcile Report in which data will get saved and can view\n              pending jobs in it.",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Sales Report : Now you can make analysis of Offline Orders Vs Online Orders through\n              filter in sale report and jewellery book in advance search.", "Customer Registration : Minor UI updates by changing position of it as first quick sale, cash\n              sale and then registration form.", "Billing : From now onwards if rate not applied for company in diamond,colorstone and misc then it\n              will show alert in save and continue button too.", "Bill Settlement : From now onwards amount will settle including discount in it."],
    },
    {
      title: "Common Updates",
      items: [
        "Payroll App :  You can make employee salary according to following options\n              \n              GROSS SALARY\n              \n              GROSS + OT\n              \n              PER HR\n              \n              GROSS + INCENTIVE\n              \n              GROSS PER UNIT",
        "Quotation : Now metal loss will get apply in quotation same as currently running in billing.",
        "Stock Melt : From now onwards memo stick from vendor will not get added in this form.",
        "Search By Stock : Add manufacturer filter in it.",
        "Rm Stock : Added filter for non reconcile bags.",
        "Closing Balance : Added filter for Credit and debit Amount .",
        "Ledger : Added User Statement Short cut in it.",
        "Item Wise Sale Report : Added payment mode and customer in it.",
        "Sample Stock Reconcile : From now onwards for reconcile and other process , make print from tag\n              print in which same tag provided as design collection.",
        "Quotation : Now onwards jobs will get check in memo and order too.",
        "Return Material : Added reference no column in it.",
      ],
    },
    {
      title: "Special Updates",
      items: ["Dashboard Amendment : Update some formulas in metal info and hyper link will get redirect to its\n              respective place too."],
    },
  ],
  R57: [
    {
      title: "Manufacturing Flow Updates",
      items: ["FG Detail New and Today Fg Details New : Added location and job type filter in it .", "Plastic Batch : Sprue wt is compulsory in it ,without sprue wt batch will not get save."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Jewellery Sale : You will get alert once round off is not added in bill.", "Outsource Report : If order is assigned to vendor then it will show order weight and if FG\n              Studded then will show stock weight in it .", "Stock Purchase : We have issued mix diamonds and take return sieve size wise, then diamonds will\n              be auto deducted from the mix in stock."],
    },
    {
      title: "Common Updates",
      items: [
        "Hybrid jewellery sale : You can make directly hybrid jewellery sale in which auto entry for\n              company diamond and color stone will take place for labour bill.",
        "VRM : In order to view on hand material with vendor you can see this report in details.",
        "Stock Book : You Can view bifurcation of metal (gold,sliver,other) in total net wt.",
        "Diamond Info : Added reference number search filter.",
        "Solitaire Diamonds Purchase : You can purchase diamonds for company stock from manufacturer too.",
        "Album : You can view design in it in according to design master display order in descending\n              order.",
        "Design Collection : Added Metal color column in it .",
        "Design Master Import : Now you can add no of parts in excel.",
        "Daily Statement : Now you can view bill verification flag here too , Also added From date \n              to To date search filter in it.",
        "Material Sale : You can maintain multiple series of material sale bill through books as currently\n              in jewellery sale.",
        "When we send the album, a OTP (OTP will receive via whatsapp) will be sent to the customer's\n              phone number for security.",
      ],
    },
    {
      title: "Special Updates",
      items: ["Whatsapp Events : From now onwards whatsapp msg sent option is available in General Ledger, Sales\n              Return, Issue Material, Return Material and Memo Issue.", "E-Invoice : Option of E-invoice added in General Sale, General Sale Return, Material Sale Return.", "Dashboard : You can view your company stock numbers how much metal,diamond, color stone,\n              solitaire is in, out and assigned to vendor.", "IRIS RFID Scan : Implementation of IRIS RFID for jewellery sale, Quotation and Memo .", "Bulk Transaction : You can issue multiple job in production for it to single employee at a time."],
    },
  ],
  R56: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Wip Reconcile : Added Group wise filter in it .\n              Filter will work in progress wise or group wise, Also\n              pending request jobs whose weight is 0 will not get added in\n              this list.",
        "WIP Report : Given option of location wise multiple\n              filter in it .",
        "QC process : You can do filing, setting and casting\n              wise QC process in manufacturing .",
        "Casting : Will have alert if metal color is different\n              in it .",
        "WIP Excel Export : Now you can export excel with\n              images for WIP report.",
        "Product Making Guide : You will see default image ,\n              Department image rotation wise.",
        'Job In Casting : You will need to press "Save & Go To\n              List" button while Add or Update Casting batch as it will\n              allow to edit UserID wise from now.',
        "Sprue cutting and Sprue grinding :\n\n              Now displays Job counts of batch.",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Retail Bill : Now you can update metal rate in it.\n              Also some label and UI updates in it.", "Retail order : Some fine tuning in it which includes\n              label and UI updates in it.", "Retail Bill :  From now onwards you will get alert\n              memo and billing wise. You can add such products list wise\n              too.", "Retail Bill : Now onwards in billing by default, all\n              values will come from retail order. you can even settle\n              received metal at the time of order in billing itself.", "Sales : You can add job wise remark in product info."],
    },
    {
      title: "E-Commerce Updates",
      items: ["Website :  Now you can view speed in Cart and Wish list too"],
    },
    {
      title: "Common Updates",
      items: [
        "Album : Now you can add up to 500 designs in an\n              album.",
        "Repairing :  Now onwards there will be auto entry for\n              diamond and color stone in customer receive as currently\n              running in order system.",
        "Repairing : Given option of metal loss in Repairing\n              too.",
        "Old metal Purchase : From now onwards RM stock\n              material will including dust in it.",
        "Repair Bill : You can view detached weight in print\n              too .",
        "Job wise issue material : Once diamond and colorstone\n              issued it will automatic redirect to metal tab to issue\n              metal too.",
        "Profit Summary Report : You can view Summary of\n              profit Customer wise, Diamond quality color wise, Color\n              stone and Metal wise .",
        "Design Collection : In this deactivated designs too\n              will come in it.",
        "VRM : You can track your vendor material information\n              from here in summary.",
        "Wastage discount : You can apply wastage discount\n              ignore collection ,category too.",
        "Design master : Now you can update brand for multiple\n              designs in design master through action update designs\n              button.",
        "Stock Purchase import: We have added purchase labour\n              on and purchase labour column. In purchase labour on : Metal\n              wt, Metal + Diamond wt, Fixed, Pieces, Gross wt.",
        "Vendor ledger : You can see colorstone balance from\n              here which will redirect to vendor VRM page.",
        "Multi currency : All the calculation in quotation\n              will run same as currently running in billing . Applied same\n              in memo issue too.",
        "Purchase against memo : You can use colorstone in the\n              same flow too.",
        "Outsource Report :  Now you can search for job\n              history for all jobs in this report which will redirect to\n              quick search.",
        "Jobs page : You can update job line id and po number\n              from jobs page.",
        "Copy button : For job number in stock book, job book\n              ,wip report and jewellery book page in it.",
        "Other charges :Bill Wise Other Charges report.",
        "PD : Now you can view full screen image in\n              Des. image process.",
        "To have continuity for issuing job and material at a time,\n              you can issue material to vendor from outsource itself.",
      ],
    },
    {
      title: "Special Updates",
      items: ["E-invoice : You can use E-invoice in material sale event too."],
    },
  ],
  R55: [
    {
      title: "Manufacturing flow updates",
      items: ["FG Summary : Outward batch replace with FG Summary page.\n                (New batch data are display in it )\n                for image view please refer stock book > image view .", "Filters : Now you can view Job work and sales order\n                filter in WIP and Today FG Detail New, FG Detail New, FG\n                Detail Date Wise.", "WIP Reconcile : Now you can reconcile WIP jobs too.", "Product Guide : Added job instructions in it & Order Size and Customer Code added too in it.", "Material Wise WIP : Plastic batch jobs too will be available in it."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Billing :", "Now you can add package weight in bulk jobs even after\n                  billing.", "Now you can apply setting rate in billing manually too.", "Pc wise labor can be applied in sale and purchase.", "You can Convert MRP to customer policy in billing.", "Retail Order : Retail Order flow is now ready to use\n                along with auto entry of received material from customer.", "Sale : Now you can change Bill mode from labour to jewellery and vice versa . Also added option\n                changing HSN in jewellery book too.", "Bill : Now you can apply handling job wise diamond wise differently too."],
    },
    {
      title: "E-Commerce Updates",
      items: ["Website :  Now you can view speed in Cart and Wish list too"],
    },
    {
      title: "Common Updates",
      items: ["Pure wt : Now you can see metal, finding and mount pure wt in locker summary .", "Design Wt variation : All jobs can be viewed in it.", "PD Order : Option of update HSN in PD Order through\n                jobs page.", "Issue Link : Added job wise issue link from Outsource\n                and repair.", "RM Report new : Now you can view RM Report for\n                pending orders manufacturer wise.", "Estimate Print : We have other charges and setting\n                charges in this print in billing.", "Job wise issue material : You will able to see job\n                wise issue material of customer and company in bold."],
    },
    {
      title: "Special Updates",
      items: [
        "Album UI : now you can see design image with description like collection, metal type etc.",
        "Sample stock : We have added quick scan page in which\n                you can able to do memo process. Also sample stock filter\n                added in Reconcile too",
        "Search by Stock : Now you can search stock ignoring\n                shape too.",
        "Product Cost Analysis : Added diamond ctw in it .\n                Also updated formula for diamond rate to fetch it from RM\n                stock if purchase price not found . Also now MISC stone\n                formula updated in it too.",
        "Deliver Wise Loss : Added summary report in which you\n                can track loss department group wise and delivery batch wise\n                loss.",
        "IGI format excel : Updates in IGI excel as government\n                form.",
        "Gold Stock - Added report which will show total RM, WIP, FG and Loss Company and customer wise",
      ],
    },
  ],
  R54: [
    {
      title: "Manufacturing flow updates",
      items: ["WIP Reconcile : Now you can reconcile WIP jobs too.", "Deliver Wise Loss : Added summary report in which you can track loss department group wise and\n                delivery batch wise loss.", "Filters : Now you can view Job work and sales order filter in WIP and Finished goods report", "WIP Reconcile : Now you can reconcile WIP jobs too", "Product Gide : Added job instructions in it"],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Billing :", "Now you can add package weight in bulk jobs even after billing", "Pc wise labour can be applied in sale and purchase.", "You can Convert MRP to customer policy in billing ."],
    },
    {
      title: "E-Commerce Updates",
      items: ["Website :  Now you can view speed in Cart and Wish list too"],
    },
    {
      title: "Common Updates",
      items: ["Pure wt : Now you can see metal, finding and mount pure wt in locker summary .", "Design Wt variation : All jobs can be viewed in it.", "PD Order : Option of update HSN in PD Order through\n                jobs page.", "Issue Link : Added job wise issue link from Outsource\n                and repair.", "RM Report new : Now you can view RM Report for\n                pending orders manufacturer wise.", "Estimate Print : We have other charges and setting\n                charges in this print in billing.", "Job wise issue material : You will able to see job\n                wise issue material of customer and company in bold."],
    },
    {
      title: "Special Updates",
      items: [
        "Album UI : now you can see design image with description like collection, metal type etc.",
        "Sample stock : We have added quick scan page in which\n                you can able to do memo process. Also sample stock filter\n                added in Reconcile too",
        "Search by Stock : Now you can search stock ignoring\n                shape too.",
        "Product Cost Analysis : Added diamond ctw in it .\n                Also updated formula for diamond rate to fetch it from RM\n                stock if purchase price not found . Also now MISC stone\n                formula updated in it too.",
        "Deliver Wise Loss : Added summary report in which you\n                can track loss department group wise and delivery batch wise\n                loss.",
        "IGI format excel : Updates in IGI excel as government\n                form.",
      ],
    },
  ],
  R53: [
    {
      title: "Manufacturing flow updates",
      items: ["WIP Report : In advance search added multiple customer, order search in it.", "Metal Loss Summary : We have emplyee name too.", "Casting : From nowownwards expected wight can be added in it.", "Casting : In Silver casting , you can add alloy too as in Gold.", "Delivery Date wise Report : Added report in which you can see summary count delivery date wise\n                customer wise and deaprtment grouping wise.", "Deliver Wise Loss : Added summary report in which you can track loss department group wise and\n                delivery batch wise loss.", "Delivery wise WIP : Added report in which you can see summary count delivery date wise customer wise\n                and deaprtment grouping wise."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Retail Bill : You can less weight from job in retail bill.", "Auto merge : From now onwards you can merge job from Stock Purchase itself. Special Notes :\n                This module is not reversible so be sure to do this operation as wanted.", 'Bulk Purchase : From now onwards you can add quantity in tagging even if not added in bulk through\n                adding special character as "-1" in quanity.'],
    },
    {
      title: "Common Updates",
      items: [
        "Audit before Sale : From this you can know billing price before sale of stock items.",
        "Cash/Bank Counting : Add petty cash in it . You can view peety cash wise opening closing in it.",
        "Material purchase report : We have added labour amount too in it.",
        "Design Wt variation : Added hyperlink in design master.",
        "Hallmark Return : Added charges in it, Form now onwards you can autopost entry in ledger too.",
        "Sales Return (old tag) : Old software sale can be entered in this software through sales return (old\n                tag) event.",
        "Stock purchase : Now you can create books in stock purchase too as in sale.",
        "Day book : New UI of day book has been updated.",
        "HUID : Now you can add job wise HUID too through this page.",
        "Delivery wise WIP : Added report in which you can see summary count delivery date wise customer wise\n                and deaprtment grouping wise.",
        "In all material management reports, description added in it.",
      ],
    },
    {
      title: "Special Updates",
      items: ["Group by Solitaire shape : By use of parent design no will make one group of design by solitaire shape\n                and will change design with its detail by selection of solitaire shape from website.", "Mobile view banners : To complete responsive or mobile view of our E-commerce website dynamic mobile\n                banner upload is available for main banner, product banner, category wise banner, default banner.", "360 image view : Now Product 360 image view is available to update on website like image and video."],
    },
  ],
  R52: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Casting : Option of colorstone weight in casting bag sticker.",
        "Job book ( Bag print 4) : If no of parts added from design master. It will show in bag print 4.",
        "Club Job : Now you wil have option of group job no .",
        "Old metal melt : Now you can issue to karigar along with tunch editable in it.",
        "RM Reconcile :\n              \n                \n                  Once cutoff you will able to view old bag number there.\n                  \n                \n                \n                  You will able to view diffrence too in RM reconcile Report.\n                  \n                \n                \n                  You can view current transactional bags in it.",
        "Once cutoff you will able to view old bag number there.",
        "You will able to view diffrence too in RM reconcile Report.",
        "You can view current transactional bags in it.",
        "Outsource Report : Added shortcut hyperlink which will get redirect to order and stock details of such\n                customers tag.",
        "Factory outward process :",
        "From now onwards, you have to track FG(factory outward) data in new report.",
        "1. Today fg detail New instead of Today fg detail.",
        "2. Fg detail New instead of fg detail.",
        "Jewellery Book : Now merged items will be viewed single in this book.",
        "Sale : Now if unmerged from billing itself, the price policy will get recalculated in it.",
        "Retail bill : Now customer address will shown here and after bill generated you can change customer\n                  and all the events will be moved to updated customer.",
        "Tools Issue : Now you can view Barcode number too in Tools issue form.",
        "Product estimate : Added option of excel export in it.",
        "Quotation : Now you can apply tax in quotation too.",
        "Stock purchase : Now you can send request for already created design to update it . Accordingly you\n                  can update it through design master request page.",
        "Daily Statement : Option of filter of verified and pending in it.",
        "Bill : Once bill verified then if it has been changed it will show again pending in grid.",
        "Daybook : Tagging details will be available in day book.",
        "Account : Now you can send freeze account sms and mail to customer.",
        "Set Metal Price : Now you can set 24k metal rate directly from [Master & Policy > Price Master > Set\n                  Metal Price].",
        "Box Weight : Now we have option of box weight system along with usge of QR in it.",
        "Sale invoice Print 1 : From now onwards in this print , extra columns are added such as fine wt,\n                  labour amount,etc.",
        "SMS : Now you can use whats app instead of SMS events . Instructions for it will be given in special\n                  page in advance for it.",
        "HSN : HSN is mandatory in quotation, sale order and all other events.",
      ],
    },
  ],
  R51: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Stock Reconcile : Additional filter of user added in stock reconcile . So from now onwards data will\n                get different user wise.",
        "Delivery Batch updates : IN WIP report you can search data according to devliery batch wise.",
        "Mfg Stock Report 4: We have added hyperlink in mfg stock report 4 which will get redirect to stock\n                valuation report along with pure weight in it.",
        "Jobs page : Added option of image view too in jobs page.",
        "Cancel Invoice : Cancel bill option will be rights based in billing. This feature rights will also\n                avaiable for E-invoice cancel billing too in sale and sale return.",
        "Misc Updates in Jobs : Now you can customize quality of misc too as currently in diamond and\n                colorstone for fresh jobs.",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Retail Bill : From now onwards you can view pure weight in it.", "Customer Registration: From now onwards in cash saleit will get redirect to retail bill.", "Stock Purchase : From now onwars you can add pcs too in tag.", "Customer Registration : Added shortcut for going to retail bill."],
    },
    {
      title: "Common Updates",
      items: ["CRM log Reports : We have added two reports in it Weekly logs and sales Rep wise logs as added in CRM\n                in call log.", "Quick tagging updates : You will see wastage as read only in it.", "Stock Availbility : By default company jobs will not show there.If check box on then you will able to\n                view it.", "Stock Book : Added filter for bulk jobs and merge jobs in it.", "Order RM Report : Now if finding checkbox off then finding weight will get merge on metal weight.", "Hash Tag : Added total counts in it and filter too in design master advance search.", "Sale Export : We have added field of FG date too in this export."],
    },
  ],
  R50: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Qc process: Now MISC weight will be shown after QC process.",
        "Sale Export : Here you can generate date wise excel of your sale report which is found in [Books\n                  Keeping > Report > Export Excel].",
        "Product Guide - Casting splits : In this update you can see if you have created B and C split with\n                main job and also if it has been in different batch during casting on this page.",
        "Product Guide - Image : In this update you can upload department wise product images which is shown by\n                default when selecting department.",
        "Search by stock : In this update you can see details by display order.",
        "Handling charge: Now you can add handling charges while creating quotation which is available in other\n                charges.",
        "Search job : Now you can see metal color details.",
        "Total net wt : This is available in Design analysis and product analysis. Total net wt available in\n                summary view.",
        "Other status in quotation : When you are making a quotation or order for job you can see its status of\n                if QC pending, or in Hallmark.",
        "FG Outward : When you are moving a job to factory outward you can see its location.",
        "Job In Casting : Now you can print casting bag details.",
        "WIP Print : In this update in WIP report print you can see job location and size details.",
        "Export Excel : In this update invoice details will be available like order type, design type.",
        "MISC price pointer consideration : In this update MISC price will consider pointer and this option is\n                available in sale and memo entry.",
        "Today Fg detail old : In this update order date, category and priority column will be available same\n                as FG details report",
        "Jobs type filter in orders : Now regular and sampleline jobs fillter available in order",
        "Color alert in Sprue : An alert message will shown when you are trying to return metal with diferent\n                color from job.",
        "E-invoice in Sale Return : Now you can generate e-Invoice for sale return.",
        "Search by stock : Now you can see your diamond stock according to diamond size master display order\n                wise.",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: [
        "Design wise search in I button : When you are doing stock purchase you can search by design wise\n                material from I-Button.",
        "Diamond info : You can see this details of lot no when you click on view button in [S/Q/C/S] column.",
        "Apply button in new tag : In this update during stock purchase when you enter metal weight and then\n                click on New tag entry button it will be auto applied.",
        "Remove color validation from quick tagging : Now in quick tagging you can change color of metal.",
        "Outsource Report : In this report we have added diamond quality column.",
        "Grouping in ColorStone : Now you can create colorstone group which is available in [Master & Policy\n                  > Material Master > Material Group]",
        "Tag Option in Stock purchase : In this update you can print a tag during stock urchase.",
        "Mount : Now you can issue mount job wise.",
        "Order summary : Now you can select multiple status in this report and it will be shown on print.",
      ],
    },
    {
      title: "Common Updates",
      items: [
        "TAG Info : In this update only active items displayed on job info which can be manage by Cart Criteria\n                page available in [ Master & Policy > E-Commerce > Cart Criteria ]",
        "Add more in album : You can add more designs by clicking add more button. When you click on add more\n                button select design view option.",
        "Auto Split : In this update you can manually add jobs weight while doing auto split.",
        "Dashboard : This is new implement where you can see all your stock and sale details and profit and\n                loss details which is available in [MIS > MIS > Dash Board]",
        "MRP jobs : Now you can add other charges of mrp base job.",
        "Due date report new : In this update all pending settlement will be shown here & fully settle amount\n                will not shown here. This report is available in [Account > report > Due date detail new]",
        "Design Wise sale Report : Now you can search by purchase count and subcategory wise filter on this\n                report.",
        "Customize all : In this update you can see colorstone shape, size and color by clicking on [Include\n                Shape] checkbox.",
        "TDS Profile : Now you can add TDS profile in master and you can use it when doing sale or purchase\n                entry.",
        "Product Estimate Report : Now you can see this report by selecting single user.",
        "TDS Report : This report is new impliment where you can see customer and supplier TDS amount.",
        "Tax profile : Now you can select tax profile during Metal settlement and Metal amount settlement.",
        "Material Purchase report : Now you can search by lot no in material purchase report.",
        "Material wise sale report : Now you can see details of design no., job no. and gross wt column a. You\n                can generate an excel by clicking on setting gear icon.",
        "Delivery charges : You can set delivery charges in [ Master &Policy > SalesCRM > Mode of deliery\n                  ].",
        "Live Gold Rate : In this update you can synchronise gold rate with live rates.",
        "TCS : In this update TCS will be available in GST Tax report, Sale register and Purchase register.",
        "Tax percentage in sales bill : You can see tax percentage in sales bill If you had applied tax in\n                percentage.",
        "Product cost analysis : Now you can see invoice material details by lot no.",
        "Wastage price import : Now you can import wastage price excel which is available in [Master &\n                  Policy > Import > Wastage Price].",
        "Add parent design no in import : In design master import we have added parent design column in excel\n                sheet.",
        "Pagination update : Now pagination available as 20, 30, 50, 100, 200.",
      ],
    },
  ],
  R49: [
    {
      title: "Manufacturing flow updates",
      items: ["Now in bag print material codes will be displayed.", "Now order type fillter is available in Stock book and WIP Report.", "In WIP Report make type fillter is available in advance search.", "During making sale order you will see add in gross wt option if the check box is on then wt will be\n                added in gross wt.", "New module is implemented in software for plastic.", "Now in material history you can find detech material entry.", "In stock melt you can add partial weight.", "In outsource report diamond and colorstone pcs & wt column will be displayed.", "In setting report now you can see misc details in it."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Now in stock purchase you will create a new tag with new tag entry button without selecting collection,\n                category and subcategory.", "Now you can enter customer code when you are converting jobs in stock book.", "When you are making retail sale bill payment must be clear (Due payment is not allowed) to save the\n                bill."],
    },
    {
      title: "Common Updates",
      items: [
        "TDS Module: Now TDS profile is available in customer, manufacturer and supplier and it will be auto\n                fetched and its effect will also shown in ledger",
        "When you are making a quotation or sale order you can change colorstone quality and color.",
        "Now all category & subcategory will be displayed in add more button in album.",
        "Now rfbag will be changed automatically every month.",
        "Now you can apply wastage by metal wt or gross wt by adding weight in weight range.",
        "Now you can add multiple images in poduct guide.",
        "In PD order a new order print has been implemented where you can see diamond ctw, color stone ctw,\n                metal wt, job no, po no and image details.",
        "Now customer registration page will auto add city, state, area and address.",
        "In area now you can select city by dropdown, also it will be shown in city area binding page.",
      ],
    },
  ],
  R48: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Repair : Now if you have given some jobs to your vendor for repairing then it will be shown as\n                hyperlink with no of jobs and weight during assiging a new reapair.",
        "Memo : Now in memo approval print all designs will be displayed as alphabatecally order.",
        "QC Process : Now you can do QC proces during MFG process, you have to create master for QC questions.",
        "Order report : Now on order page you can view total quote, eta and remaining jobs.",
        "Loss Percentage : Now you can see loss percentage in transaction page. If loss percentage is less than\n                setted percentage it will be shown in green and if greater then setted perventage than it will be in\n                red.",
        "Casting : Now in casting you can see aded metal and added alloy in batch.",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Product Altereation : Now in product alteration you can see newely added material in print."],
    },
    {
      title: "E-Commerce Updates",
      items: ["Fillter : On diamond store you can apply and reset fillter according to your choice."],
    },
    {
      title: "Common Updates",
      items: [
        "Multi Currency : Now in reports you can fillter currency by selecting it from dropdown.",
        "Design Analysis : Now you can see product image in Design Analysis by clicking on it. You can see\n                seperate tab for it.",
        "Quotation :\n              \n                \n                  Now in quotataion you can apply fixed charges.\n                \n                \n                  In quotation excel file you can see total diamond weight in it.\n                \n                \n                  Now in quotation you can add/less or discount amount.\n                \n                  In quotataion you can add iunstruction and it will be shown in print.",
        "Now in quotataion you can apply fixed charges.",
        "In quotation excel file you can see total diamond weight in it.",
        "Now in quotation you can add/less or discount amount.",
        "In quotataion you can add iunstruction and it will be shown in print.",
        "Merge jobs : Now you can merge jobs weight from stock book.",
        "Now onwards state will be auto filled during customer create.",
      ],
    },
  ],
  R47: [
    {
      title: "Manufacturing flow updates",
      items: ["RM Reconcile : You can match your physical stock with RM Reconcile process.", "SKU No & Line No : Now SKU No and line no will be dislayed on jobs page."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["In retail bill solitaire diamond details will be displayed and you can customise all other details also\n                you can purchase old metal."],
    },
    {
      title: "E-Commerce Updates",
      items: ["Banner : Now you can remove banner from banner upload page.", "EVO : Now you can add new customers using our EVO app.", "Metal Purity : Now onwards you can see metal purity on your website."],
    },
    {
      title: "Common Updates",
      items: [
        "TDS Module: Now TDS profile is available in customer, manufacturer and supplier and it will be auto\n                fetched and its effect will also shown in ledger",
        "When you are making a quotation or sale order you can change colorstone quality and color.",
        "Now all category & subcategory will be displayed in add more button in album.",
        "Now rfbag will be changed automatically every month.",
        "Now you can apply wastage by metal wt or gross wt by adding weight in weight range.",
        "Now you can add multiple images in poduct guide.",
        "In PD order a new order print has been implemented where you can see diamond ctw, color stone ctw,\n                metal wt, job no, po no and image details.",
        "Now customer registration page will auto add city, state, area and address.",
        "In area now you can select city by dropdown, also it will be shown in city area binding page.",
      ],
    },
  ],
  R46: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Now in metal loss summary actual weight is available in bracket.",
        "Now product guide page will stay for 15 minutes.",
        "Now in sales order you can add line ID, Product ID and batch no, also you can search it on jobs page\n                and jewellery book.",
        "You can split jobs during accepting eta request.",
        "In search job you can see stamping details.",
        "Now in setting report diamond ctw will be displayed.",
        "Now in engage material color stone criteria will be checked, if criteria not found then you can not\n                engage material.",
        "Now you can dispatch product alteration and assign to repair invoices. It will be available to shipment\n                wheere you can print amount on sticker too.",
        "Now in quotation finding will be shown separately.",
        "Now loss restriction widow will open separately.",
        "Now dust weight will be auto generated and on dust hyper link detech process will start.",
      ],
    },
    {
      title: "Common Updates",
      items: [
        "Now you can update due days in material purchase also after creating an invoice.",
        "Now in product cost analysis customer name will be shown and amount profit will show default data.",
        "Now in stock purchase you can purchase loose metal with is pcs and weight. Also you can see its report\n                which is available in [Inventory > Stock MGMT > Loose Purchase].",
        "Before sending mail now you will get an confirmation message to send a mail.",
        "Now you can issue and return material by pcs.",
        "You can print pay slip without header in it.",
        "In material sale you can add remarks upto 500 alphabets.",
        "In quotation you can apply rate to all findings and you can search diamond shape in quotation too.",
        "When you are creating an employee you can add middle name of employee.",
        "We have implemented a new report for stock tally which is available [MIS > Manufacturing > Stock\n                  Tally]",
        "Now you can export an excel of online designs.",
        "Certificate no will be print in sale invoice and memo issue print.",
        "Now you can verify stock purchase bills same as sale bill.",
        "In purchase against memo you can add weight in it.",
        "Now you can add TCS in tax profile and you can add upto three decimals in it.",
        "Now you can create diamond sieve size wise group which will be shown in quotation print.",
        "Now you can purchase old gold from purchase bill option.",
        "We have implemenrted a new report for Sales GST which is available in [Account > Report > GST\n                  Report].",
        "Now in issue material and return material company name also be displayed.",
        "In regular tag 7 MRP calculation will work as Current MRP * 3 / 7.",
        "Now you can upload rollover image same as uploading other images.",
        "Now onwards city, area ,country and zip coce will be auto binded.",
      ],
    },
  ],
  R45: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Now you can see entries of product alteration and repair in general ledger.",
        "Now you can add metal rate in product alteration receive.",
        "In material history you can see both bags detail graded from and graded to.",
        "When you are creating a quote then you will get an alert message for company jobs or customer jobs.",
        "Now you can search by metal and jewellery size in stock summary.",
        "We have implemented a new report which is available in [Manufacturing > Report > TV Terminal\n                  Display] Where you can find all your working details of production department. You need to create\n                a group for TV Terminal Display.",
        "In RM Reconcile you can add weight manually or you can add it by weighing scale.",
        "Now you will get details of material engage report.",
        "Now in WIP report in advance search metal type by default it will be gold selected.",
        "Nowonwards in production silver weight will be calculated same as gold.",
        "Now you can melt jobs which are in production and also you can melt jobs which are created by stock\n                purchase.",
        "We have implemented a new report for casting batch data which is available in [MIS > Manufacturing\n                  Analytic > Casting Report]",
        "We have implemented a new report for casting batch data which is available in [MIS > Manufacturing\n                  Analytic > Casting Report]",
        "Now priority font color will be same every where as priority will be shown.",
        "Now stamping details will be shown in product guide if you had added it.",
        "In Tv Terminal display only regular jobs data and no. of jobs, weight will be shown.",
        "Now in order print job's color will be printed on print.",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Now you can add package weight in quick tagging", "Now you can add jobs whose mrp has been set.", "We have imaplemented a new report as sales analysis which is available in [Books Keeping > Report >\n                  Sales Analysis]", "We have imaplemented a new report as Pending to purchase which is available in [Books Keeping >\n                  Report > Pending to purchase] where you will get details of jobs whose process of stock purchase\n                is not done."],
    },
    {
      title: "E-Commerce Updates",
      items: ["Now you can set mrp of product in backend from mrp price which is available in [Ecatlog & backoffice\n                  > Price calculation > MRP Price]"],
    },
    {
      title: "Common Updates",
      items: [
        "Now you can add remarks and set promise date in customer due date summary.",
        "You can add weight range in wastage price and if selected any in all other criteria then fillter will\n                ignor criterias.",
        "Now in customer return you can add tounch in finding and it will also show in ledger.",
        "Now in set mrp updated value will be shown.",
        "You can create books in sale which is available in [System admin > Company setup > Books]",
        "In labour set you can add weight loss % and if checkbox is on then making loss will not include in\n                metal weight, gross weight and metal + diamond weight.",
        "Now employee cannot activate/deactivate design without having rights.",
        "In finish goods report mount weight will be shown in total net weight and diamond handlling amount will\n                be shown in total dia. Amount.",
        "Now you can add mobile no digits upto 12.",
        "In customer registration now addressline 1 is not a mandatory field.",
        "Now in cash and bank issue and return button will be renamed as pay and receive.",
        "Now total of total amount will be shown in customer wise sale report.",
        "Now you can add remarks of product in product making image after uploading an image.",
        "Now in style bank import you can add parent design no in excel.",
        "Now discount will be shown in invoice print 3",
        "Now you can export excel of summary ledger.",
        "Now you can view stock transfer logs up to 4 months.",
        "In FG Stock alert you can add weight range in it.",
        "Now you can add customer receive directly from sale bill.",
        "We have implemented new report material wise stock report where you will get details of all material\n                including pcs, weight quality, size, shape. This report is avialble in [Books Keeping > Material\n                  report > Material wise stock report].",
        "Now you can search remarks in jobs, WIP Report, and Jewellery Book.",
        "Now you can purchase old metal same as doing material purchase.",
        "In saving scheme you can settle amount or can give discount amount.",
        "Now you can upload multiple image at a time.",
      ],
    },
  ],
  R44: [
    {
      title: "Manufacturing flow updates",
      items: ["Now in jobs in casting if you had selected two different color jobs then you will get an alert message.", "Now you can see jobs status as per your production.", "Now in quick search you can see jobs location.", "Now in material wise wip you can view customer name and company name too.", "If you have not selected on button in MFG Department for specific department than you can not unlock\n                material in perticular department."],
    },
    {
      title: "Common Updates",
      items: [
        "In stock purchase and in quick tagging you can see tounch.",
        "Now you can purchase mount and findings too.",
        "Now you can customise all your material in quotation same as stock purchse.",
        "In closing balance you can add more details in remarks.",
        "In tax profile you can add three decimal value.",
        "In balance sheet(old) you can see round off value in it.",
        "Now you will able to see finding separately in quotation print.",
        "Now pages will be shown as 20,50,100,500.",
        "Now invoice will not deleted if you removed your job.",
        "In memo you can print rough estimate.",
        "In memo approval print now only category prefix and job no will be shown annd if you have added terms\n                and conditions in default company info then it will show in print.",
        "Now album price will not show in SMS and Mail.",
        "Now ship to address will be shown in credit note bill print.",
        "Now you can apply default rate shipment delivery note print.",
        "In memo approval print you can see company name too.",
        "Now sales representative will also receive sms copy of customer who are binded with them.",
        "In jewellery book print if jobs are in memo then customer name will be shown.",
      ],
    },
  ],
  R43: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Sale Report- Now you can view Customer and Company Diamond & Color Stone seperately in summary\n                section.",
        "Quotation : Now you can easily convert all diamonds into Color Stone of all designs in single click.",
        "Delivery Batch: Now you can also view QC Status of job.",
        "Transaction: We've interchanged postion of 'Unlock Engage' & 'Issue Job' button. It's been done to\n                eliminate mistake in which user accidantly clicks on Issues Job in department instead of 'Unlock\n                Engage'.",
        "Now you will be notified while creating Customer's Quotation & Sales Order if particular design is\n                already available in Stock Book or WIP.",
        "Sketch: Now you can view image in full screen.",
        "RM Stock: Now you can also view Diamond & CS Pcs in label print.",
      ],
    },
    {
      title: "Common Updates",
      items: ["Repair Print Jewellery Sale: Added new print in which your customer can view following details: 1)\n                Received Jewellery : Details of jewellery recieved for repair. 2) Repaired jewellery : Details of\n                jewellery after repairing is completed. 3) Added material : Details of extra material added. 4) Detached\n                materail : Details of detached material.", "Now you can Split Job into multiple jobs. [Books Keeping >> Sales Book >> Auto Split].", "Daily Statement - Now entries of each transaction will be shown in this report. Previously, few events\n                were left out from this.", "Invoice Wise Sale Report: Added Company Name along with customer code."],
    },
  ],
  R42: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Customer Active Report: Now you can view customer wise Net wt of all jobs of following events: Quotes\n                Only, Orders, WIP, In QC & Dispatched. [Sales CRM >> Report >> Customer Active Report]",
        "Repair Material Report: Added new report with details of material returned/loss incurred from repair\n                job. Earlier, customer receive voucher was generating for this. [Books Keeping >> Material Report >>\n                Repair Material]",
        "Quotation & Sales Order: Now you can search designs according to Diamond Shape and then can change\n                specific material details in all designs in single click. You will find Diamond Shape search in 'Advance\n                Search'.",
        "Now you can define, which material (metal, diam, cs or misc) should be allowed to return from specific\n                department. To do so, go to MFG Department master and enable/disable material for each department.",
        "Now you can also Merge Finding bags in RM Stock.",
        "FG Detail report: Now you can filter job according to Job type (Regular, Sample Line or Repair).",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Old Gold Entry: Now you can also make old gold entry from Payment tab in sale invoice. Also, amount of\n                old gold is also displayed here along with Cash & Bank payments.", "Old Gold Refining: Now use new page to issue & receive of melted metal. Go to Inventory >> Stock\n                  Melt >> Melt Refining. Also added Old Gold Report to view profit earned in the process\n                [Inventory >> Stock Melt >> Old Gold Report].", "Festival Master: Now you can also mention Festival in customer's profile. To add Festival master, go\n                to Master & Policy >> User Master >> Festival."],
    },
    {
      title: "Common Updates",
      items: ["My Account: Now all values such as Sale, Orders, Party Balance, etc. will display in currency of\n                respective customer. Also, your default print in Back-end will open when will customer open print.", "Now you can also view job count in E-Audit (Purchase Register & Stock Register).", "Now you can de-active any customer's account with help of Active/De-active option available with each\n                customer. Such customer's name will not be binded while making any entry/invoice such as Jewellery Sale,\n                Customer receive, etc. Also, you can add remark while de-activating.", "Currency Exchange rate: Now you can set exchange rate in 4 decimal points."],
    },
  ],
  R41: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Required Material Report: Added new report as RM Stock from which you can view order wise requirement\n                of raw material.   [Sales CRM >> Sales >> RM Stock]",
        "ETA Request: Now user cannot place ETA request without rights of any location, i.e. user must have\n                rights of location to plae ETA request.",
        "Now you can filter jobs according to Priority in Stock Book.",
        "Stock Book: Now option to return job to manufacturing will be visible to employee based on permission.\n                 [User >> Staff >> Employee >> User Permission >> Return Production Job]",
        "Adhoc Package Mail: From now, in Regards section, Email id and Name of customer's reference user will\n                be displayed instead of user who have logged when mail is sent.",
        "Now you can add Repair Jobs from customer and assign same to Production.  [Sales CRM >> Repair\n                  >> Receive To Repair]",
        "From now, handling charges will get applicable if diamond is of customer.",
        "Quotation: Added E-Signature feature in Quotation Email and SMS.",
        "Transaction: Now user can Return Material from any locker despite of material being issued from some\n                other locker.",
        "Now you can allow departments whose jobs should be allowed to issue to Casting batch. Just enable\n                'Before Casting' feature in MFG department master for particular departmet to do so. Earlier, only\n                Pending Request & Wax Setting Receive jobs were only allowed to add in Casting. Also, you can hide\n                weight column from transaction for any department by using 'Allow Wt' feature.  [Master & Policy\n                  >> Manufacturing >> MFG Department]",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Added new column as 'MFG Design#' in Outsource report.", "Quick Tagging: Now you can also input Gross weight same as currently working in Stock Purchase.", "Stock Purchase : Now you can mention 'Purchase MRP' as well as 'Sale MRP' of job while making it's\n                purchase entry.", "Quick Tagging : For only gold products , easy way of entry of products through generate button."],
    },
    {
      title: "Common Updates",
      items: [
        "Material Sale Print: Now actual quality & weight of Metal & Mount will be displayed in print. Earlier\n                24K was showing regardless of whatever purity (18K, 14K, etc.) is added in entry.",
        "Enhancement in Average rate calculation in Stock report.  [Account >> Reports >> Stock Report]",
        "The effect of detached material will not be applied automatically in ledger of particular\n                manufacturer. You can post it's effect by clicking on 'Post To Ledger' feature given for each issue\n                material voucher.",
        "Design Master: Added feature to Auto Generate Design#.",
        "Added new column as Purchase Mode (Labour Purchase & FG Purchase) in Stock Purchase Return and\n                Jewellery Sale Return.",
        "Now you can also view Profit Percentage in Product Cost Analysis report.  [Books Keeping >>\n                  Report >> Product Cost Analysis]",
        "Now you can view Ledger details by applying pre-defined filters for 30,60 & 90 days. Also, from now,\n                option to apply date manually will be disabled.",
        "Mount Purchase: Now you can also apply rate 'On Pcs'.",
        "Now you can also maintain stock of MISC material and can use this in jewellery same as currently\n                working for Diamond and Color Stone. All entries such as Material Purchase, Issue Material (to Vendor),\n                Engage Material, Material Sale, etc. are now available for MISC material too. [Master & Policy >>\n                  Material Master >> MISC] [Inventory >> RM Stock >> MISC] \n                What is MISC?    MISC are stones which are used in jewellery but weight of such\n                stones are measured in Grams. Also, you can set weight limit (in gms as well as in %) for MISC which\n                need to be displayed in Sale Invoice. For e.g., 2 gms MISC stone is studded in jewellery and you have\n                set 80% limit, then only 1.6 gms MISC will displayed in Sale Invoice and 0.4 gms will be added in Metal\n                Wt. To set such limit for each MISC, go to Master & Policy >> Price Master >> Labour Set. Now edit any\n                Labour Set and click on Save & Continue to set Ceiling Value for each MISC.",
        "Material Wise Sale Report: Added new report to view details of Material used in sold jewellery.\n                 [Books Keeping >> Material Report >> Material Wise Sale Report]",
        "Added new column as Country in Lead Customer grid.",
        "Product Cost Analysis: Added filter for Company Type in Advance search.",
        "Folio view: Now you can view merged ledger of multiple accounts. Just create one Folio by adding such\n                accounts and search with Folio's name in ledger.  [Master & Policy >> Account >> Folio]",
        "General Sale: Using this feature you can create invoice for any product or service apart from\n                Jewellery, Precious Stones & Metal.  [Account >> Account >> General Sale & General Sale Return]",
        "Settlement: Now you can make settlement entry for All Accounts. Earlier it was available only for\n                Customer, Supplier & Manufacturer.",
        "FG stock Melt: Now if customer's material is used in job, then Diamond/Color Stone will be added in\n                material bag of specific customer. Earlier it was added in company stock.",
        "Advance Price Policy: Now you can set price policy for selected criteria in Wastage Price. \n                  [Master & Policy >> Price Master >> Wastage Price]  Please contact our support executive for\n                more details",
        "Now you can add all jobs in Product Estimate. Earlier 'In Stock' jobs were only allowed to be added in\n                estimate.",
        "Added 'Only Size Grade' feature in Stock Access permission for employee. This feature helps you to\n                assign diamond & color stone grading option for only size. Clarity & Color grading options will be\n                disabled for such user.",
        "Material Purchase: Now you can update Labour rate for Mount/Findings.",
        "From now, Metal rate will not apply by default in Labour Sale.",
        "Due Date report: Now you can also check dues of Manufacturer and Supplier in this report including\n                'over due' and 'bill date wise due'.",
        "Stock Bifurcation Report: Now you can search jewellery stock according to gross weight range\n                bifercation in Stock Book & Jewellery Book.  [Master & Policy >> Sales CRM >> Stock Weight\n                  Bifurcation]",
        "Metal Price: Now you can set metal rate for both Purchase and Sale seperatly.",
        "Account stock report: Added pre-defined date filters such as Last Day, Current Month, Last Month, Last\n                3 Month, Last Financial Year & Current Financial Year.",
        "Ecat Ad Hoc Package: Now you can also select Start Date and Start Time while changing customer\n                package.",
        "Now you can Unmerge jobs also while making jewellery sale invoice. Just select job/s and click on\n                Unmerge button.",
        "MRP filter in Jewellery Book: Now you can filter products as per MRP range, set in Price Range master.\n                 [Master & Policy >> Sales >> Price Range]",
        "Labour set (Fix Making): Now you can select which weight should be considered to apply Fix Making\n                charges (Metal wt or Gross wt or Metal+Diam).",
      ],
    },
  ],
  R40: [
    {
      title: "Manufacturing flow updates",
      items: ["Expected Loss restriction - Removed this validation for jobs whose metal type is Silver.", "Quotation & Sales Order: Now you can remove Metal rate from all designs by using 'Metal Rate Zero'\n                feature.", "Added 'Location' filter in Advance Search in Sample Stock page.  [Inventory >> Stock MGMT >>\n                  Sample Stock]", "Enhancement in Setting report."],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: ["Jewellery Sale: UI enhancements in payment tab.", "Return material: Now 'Broken' & 'Lost' material will be displayed seperately in Print."],
    },
    {
      title: "Common Updates",
      items: [
        "Repair Voucher: Now you can apply separate Tax rates for repair invoices. Click on 'Repair Voucher' in\n                customer info section while making new sale invoice. To define tax rate and HSN of Repair, go to\n                'Master & Policy >> Account >> Item Master' and search for Repair. Also removed 'Due\n                  Date' column in all print formats for repair invoices only.",
        "Cash & Bank Voucher Print: Displayed 'Address' with Company Name in Paid To/Received From column.",
        "Bank Reconciliation: Now you can filter 'Cleared & Uncleared' transactions and also can remove 'Bank\n                Date' from any entry even when it is set.",
        "Sales Order Type: Added new feature to select order type whie creating order. [Master & Policy\n                  >> Sales CRM >> Order Type]",
        "Detach Material: Now onwards, Issue Material voucher for detached material will be created for date of\n                Repairing voucher instead of date on which material is detached.",
      ],
    },
  ],
  R39: [
    {
      title: "Manufacturing flow updates",
      items: [
        "Now you can define department wise 'Unlock Material Option' in master. Earlier, Unlock material was\n                only limited with setting department.  (Master & Policy >> Manufacturing >> MFG\n                  Department)",
        "Dust Collector Report: Added new column as 'Net wt'.",
        "Setting Report: Added 3 new columns as Material, Quality & Color.",
        "Order Info Report: Added new report to view order wise remark entered in each job. (Sales CRM\n                  >> Reports >> Order Info)",
        "Finding Master update: Added new column as 'Finding Accessory Code'.",
        "Added Engage Material Tag to print tags with details of engaged material on QR Code enabled tags.\n                Note: This feature is only available in 'Engage Material New' page.",
        "Added diamond to gold ratio in CAD Info. D/G Ratio = Total Diamond Ctw/Total Net wt. (PD >> PD\n                  Order >> PD Order List)",
        "Jobs In Casting: Now you can filter jobs as per Priority while adding jobs in casting batch.",
        "Stamping Details: Now you can add/update stamping details while creating sales order.",
        "Finding Engage: Now you can also engage Findings same as Diamond & Color Stone. Note: This\n                feature is only available in 'Engage Material New' page.",
        "'Like' feature for uploaded sketch images in sketches list.",
        "Quotation: Added Metal color in PDF.",
        "Product Cost Analysis: Calculation update for 'Pure wt' of jobs (only manufacturing jobs).",
        "Department wise loss: Now you can set department wise gross weight limit to ignore expected loss\n                restriction. For e.g. In Filing department, you have set 2% in expected loss and 3 gm in 'Ignore wt\n                Upto'. Now, while returning job from Filing, software will not apply expected loss restriction for jobs\n                whose gross weight is 3 gms or less.  (Master & Policy >> Manufacturing >> MFG\n                  Department)",
        "Transaction: Now you can view Last 3 losses registered in any design. Just click on 'Last 3 Loss'\n                hyper-link to view data.",
        "Transaction: Now system will give alert if any design# is assigned multiple times in same department.\n                System will compare designs according to 'Design#', 'Metal Type', 'Metal Quality' and 'Metal Color'.",
        "Quotation & Sales Order: Now you can also view availability of Finding in Stock Availability feature.",
      ],
    },
    {
      title: "Wholesale & Retail flow Updates",
      items: [
        "Stock Purchase: Added column to add 'MFG DESIGN NO'.",
        "Advance KYC: Now you can add details such as name, address, contact, birth date, etc of customer's\n                family members too.  (User >> Customer >> Customer >> User Info >> Staff/Family Info)",
        "FG Stock Alert Report: Now you can view required quantity for FG Stock according to defined minimum\n                quantity and available quantity in Stock & Memo. (Master & Policy >> Sales CRM >> FG Stock\n                  Alert)",
        "Now 'Making charges' on Gold Rate% will also be applied in Memo and Memo return.",
        "Product Estimate feature to give estimated price to customer with print.(Sales CRM >> Sales\n                  Book >> Product Estimate)",
        "Repair Return: Added option to add 'Mount' same as Diamond & Solitaire.",
        "Now you can quickly add data of Job based Stock Purchase with help of import feature.  (Master\n                  & Policy >> Import >> Outsource Job Import)",
        "Issue Material: Now you can quickly issue material to vendor according to assigned PO. Just enter PO#\n                in issue material window to get list.",
      ],
    },
    {
      title: "Common Updates",
      items: [
        "Added 'IMPS' & 'UPI' in payment mode options in Bank transaction.",
        "Label name change of Repair: We've changed label name of Repair feature. New labels are as follows:\n                Jobs In Repair = Product Alteration, Stock in Repair = Alteration Stock and\n                Repaired Jobs = Product Alteration Receive.",
        "Alteration type: Now you need to select 'Alteration Type' while assigning job for alteration. To\n                create alteration types masters, go to Master & Policy >> Sales CRM >> Alteration Type.",
        "Design Collection: Added column for 'Product Type' & 'Brand'.",
        "Now you can upload image of particular Color Stone & Finding in master.  (Master & Policy >>\n                  Material Master >> Color Stone/Finding)",
        "Sales Report: Now 'Setting' and 'Handling' charges will be displayed separately in Summary data.",
        "Displayed Company name with Customer code at many pages such as Jewellery sale, Jobs, Customer\n                Receive, etc.",
        "Now you can customize diamond's color too from stock book.",
        "CRM: Now you can also search with company name of customer.",
        "Added column to enter 'CIN#' in company detail of all users (customer, manufacturer, etc.) and also in\n                company details of your company (System Admin >> Company Info >> Default Company Info).",
        "Parent Design: Now you can add 'Parent Design number' in each design. With the help of Advance search,\n                you can also search all designs of any specific Parent design.",
        "Wastage Price Master: Now you can set Making rate instead of wastage. Just enable 'Set as making'\n                check-box if you want to set entered value as making.",
        "Displayed 'Brand Name' with Job number in all pages where job is added for Inward or Outward of\n                jewellery.",
        "Mode Of Delivery: Now you can select Delivery Mode (shipping company) while creating sales order. The\n                delivery charges will be added in invoice as per the charges mentioned for each delivery mode in master.\n                 (Master & Policy >> Sales CRM >> Mode Of Delivery)",
        "Feature to upload Journal Entries from excel.  (Master & Policy >> Import >> Journal)",
        "Daily Statement and Transaction report: Hyper-link on account name to open ledger.",
        "E-signature feature is now also available for Cash & Bank SMS and Sales Order Email.",
        "Design Master: Changes in material info section and now details of Findings can also be added in\n                material details.",
      ],
    },
  ],
};
