export const HELP_VIDEOS = [
    {
        id: 'hv-1',
        title: 'Mapping Master',
        slug: 'mapping-master',
        category: 'Inventory',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'vneUiLcV7bg',
        youtubeIdEnglish: 'vneUiLcV7bg',
        youtubeIdHindi: '6Ympj0qOMR0',
        desc: 'Mapping Master'
    },
    {
        id: 'hv-2',
        title: 'RM Reconcile',
        slug: 'rm-reconcile',
        category: 'Inventory',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'QVtIY84FHowa',
        youtubeIdEnglish: 'QVtIY84FHowa',
        youtubeIdHindi: '0vyxE7kHuH8',
        desc: 'RM Reconcile'
    },
    {
        id: 'hv-3',
        title: 'Dust collector - refining',
        slug: 'dust-collector-refining',
        category: 'Karigar (Mfg)',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'RnapeYurW8k',
        youtubeIdEnglish: 'RnapeYurW8k',
        youtubeIdHindi: 'rAYBaJqY_fY',
        desc: 'Dust collector - refining'
    },
    {
        id: 'hv-4',
        title: 'Lineid',
        slug: 'lineid',
        category: 'Sales & CRM',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'Rpd_3dUCKGI',
        youtubeIdEnglish: 'Rpd_3dUCKGI',
        youtubeIdHindi: 'EEkFXA6aq9k',
        desc: 'Lineid'
    },
    {
        id: 'hv-5',
        title: 'Set mrp',
        slug: 'set-mrp',
        category: 'Billing & GST',
        duration: '3:00',
        views: '1.2K',
        youtubeId: '5XQMLHOFtK8',
        youtubeIdEnglish: '5XQMLHOFtK8',
        youtubeIdHindi: 'CyAQtiViZQw',
        desc: 'Set mrp'
    },
    {
        id: 'hv-6',
        title: 'Cache clear',
        slug: 'cache-clear',
        category: 'General',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'x-z52xjgLRk',
        youtubeIdEnglish: 'x-z52xjgLRk',
        youtubeIdHindi: 'VKysdH_J9w0',
        desc: 'Cache clear'
    },
    {
        id: 'hv-7',
        title: 'Stock transfer',
        slug: 'stock-transfer',
        category: 'Inventory',
        duration: '3:00',
        views: '1.2K',
        youtubeId: '0NuL-hmBYHo',
        youtubeIdEnglish: '0NuL-hmBYHo',
        youtubeIdHindi: 'MGr1zo3gtEA',
        desc: 'Stock transfer'
    },
    {
        id: 'hv-8',
        title: 'Finding creation',
        slug: 'finding-creation',
        category: 'Karigar (Mfg)',
        duration: '3:00',
        views: '1.2K',
        youtubeId: '8GycuD-qhjI',
        youtubeIdEnglish: '8GycuD-qhjI',
        youtubeIdHindi: '8jChJ5vI-HY',
        desc: 'Finding creation'
    },
    {
        id: 'hv-9',
        title: 'Finding conversion',
        slug: 'finding-conversion',
        category: 'Karigar (Mfg)',
        duration: '3:00',
        views: '1.2K',
        youtubeId: '0z4_uME-gac',
        youtubeIdEnglish: '0z4_uME-gac',
        youtubeIdHindi: 'LRJcFd_1Bmw',
        desc: 'Finding conversion'
    },
    {
        id: 'hv-10',
        title: 'Customer company name change',
        slug: 'customer-company-name-change',
        category: 'Sales & CRM',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'kdJViBfHk_E',
        youtubeIdEnglish: 'kdJViBfHk_E',
        youtubeIdHindi: 'jZ2FcjjZscY',
        desc: 'Customer company name change'
    },
    {
        id: 'hv-11',
        title: 'Stock book Finding Labour',
        slug: 'stock-book-finding-labour',
        category: 'Karigar (Mfg)',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'c3tWydQTNGA',
        youtubeIdEnglish: 'c3tWydQTNGA',
        youtubeIdHindi: 'Eo9EcX9hC9U',
        desc: 'Stock book Finding Labour'
    },
    {
        id: 'hv-12',
        title: 'Policy verification',
        slug: 'policy-verification',
        category: 'General',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'Jp6mSQijx1o',
        youtubeIdEnglish: 'Jp6mSQijx1o',
        youtubeIdHindi: '_CJ_h1Ql2gg',
        desc: 'Policy verification'
    },
    {
        id: 'hv-13',
        title: 'pending memo and jewllery book',
        slug: 'pending-memo-and-jewllery-book',
        category: 'Inventory',
        duration: '3:00',
        views: '1.2K',
        youtubeId: '9fgoDL0DkJI',
        youtubeIdEnglish: '9fgoDL0DkJI',
        youtubeIdHindi: 'kuk_2mi14wY',
        desc: 'pending memo and jewllery book'
    },
    {
        id: 'hv-14',
        title: 'Cancel bill restore',
        slug: 'cancel-bill-restore',
        category: 'Billing & GST',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'C5V6JptDD-o',
        youtubeIdEnglish: 'C5V6JptDD-o',
        youtubeIdHindi: 'zVHPef1F4yA',
        desc: 'Cancel bill restore'
    },
    {
        id: 'hv-15',
        title: 'Lab add',
        slug: 'lab-add',
        category: 'Inventory',
        duration: '3:00',
        views: '1.2K',
        youtubeId: '7s5uvcw5bTQ',
        youtubeIdEnglish: '7s5uvcw5bTQ',
        youtubeIdHindi: '30FepReUXlk',
        desc: 'Lab add'
    },
    {
        id: 'hv-16',
        title: 'Huid and ceritficate add',
        slug: 'huid-and-ceritficate-add',
        category: 'Barcode & Printing',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'mUUHL37yqCw',
        youtubeIdEnglish: 'mUUHL37yqCw',
        youtubeIdHindi: 'BRHPKp-DN6Y',
        desc: 'Huid and ceritficate add'
    },
    {
        id: 'hv-17',
        title: 'Sale tag',
        slug: 'sale-tag',
        category: 'Barcode & Printing',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'E-JlgnaIdmE',
        youtubeIdEnglish: 'E-JlgnaIdmE',
        youtubeIdHindi: 'EOyK0y5MhJk',
        desc: 'Sale tag'
    },
    {
        id: 'hv-18',
        title: 'Memo Tag',
        slug: 'memo-tag',
        category: 'Barcode & Printing',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'ql3Osiyj1JQ',
        youtubeIdEnglish: 'ql3Osiyj1JQ',
        youtubeIdHindi: 'l9Y6SDxgn5Y',
        desc: 'Memo Tag'
    },
    {
        id: 'hv-19',
        title: 'Job moved to Production',
        slug: 'job-moved-to-production',
        category: 'Karigar (Mfg)',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'rcAm6DETIC0',
        youtubeIdEnglish: 'rcAm6DETIC0',
        youtubeIdHindi: '4Eb80R2FfRs',
        desc: 'Job moved to Production'
    },
    {
        id: 'hv-20',
        title: 'Loss recovery',
        slug: 'loss-recovery',
        category: 'Karigar (Mfg)',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'skNxNH41wmM',
        youtubeIdEnglish: 'skNxNx41wmM',
        youtubeIdHindi: 'OZnA6qZaSdQ',
        desc: 'Loss recovery'
    },
    {
        id: 'hv-21',
        title: 'Loss recovery from Admin login',
        slug: 'loss-recovery-from-admin-login',
        category: 'Karigar (Mfg)',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'EXjlzbOlr9s',
        youtubeIdEnglish: 'EXjlzbOlr9s',
        youtubeIdHindi: 'oFe9AHE2AFY',
        desc: 'Loss recovery from Admin login'
    },
    {
        id: 'hv-22',
        title: 'Club job (mfg job book)',
        slug: 'club-job-mfg-job-book',
        category: 'Karigar (Mfg)',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'CrdD_6hwT9U',
        youtubeIdEnglish: 'CrdD_6hwT9U',
        youtubeIdHindi: 'gKs4lU2ru9k',
        desc: 'Club job (mfg job book)'
    },
    {
        id: 'hv-23',
        title: 'Sample line tag',
        slug: 'sample-line-tag',
        category: 'Barcode & Printing',
        duration: '3:00',
        views: '1.2K',
        youtubeId: 'kVe6cgg61qY',
        youtubeIdEnglish: 'kVe6cgg61qY',
        youtubeIdHindi: 'faHBNZg7zwQ',
        desc: 'Sample line tag'
    }
];

export const HELP_CATEGORIES = [
    "All",
    ...Array.from(new Set(HELP_VIDEOS.map(video => video.category)))
];
