export const trainingFlowFlat = [
    { order: 1, module: "User", section: "Company Type" },
    { order: 1, module: "User", section: "Company Type master" },
    { order: 1, module: "Company Details Setup", section: "Books" },
    { order: 2, module: "User", section: "Customer" },
    { order: 2, module: "User", section: "Customer (B2B)" },
    { order: 3, module: "User", section: "Customer Registration" },
    { order: 3, module: "User", section: "Customer Registration (B2C)" },
    { order: 4, module: "User", section: "Admin" },
    { order: 4, module: "User", section: "Admin Reset Password" },
    { order: 5, module: "User", section: "Employee" },
    { order: 5, module: "User", section: "Employee Reset Password" },
    { order: 6, module: "User", section: "Manufacturer/Vendor" },
    { order: 6, module: "User", section: "Manufacturer Vendor" },

    { order: 7, module: "Masters & Policy", section: "Department And Designation" },
    { order: 7, module: "Masters & Policy", section: "Department & Designation" },
    { order: 8, module: "Masters & Policy", section: "Brand , Product Type , Setting Type" },
    { order: 8, module: "Masters & Policy", section: "Brand, Product Type, Setting Type" },
    { order: 9, module: "Masters & Policy", section: "Mapping Master" },
    { order: 9, module: "Inventory", section: "Mapping" },
    { order: 9, module: "Inventory", section: "Mapping Master" },
    { order: 10, module: "Masters & Policy", section: "Metal Master" },
    { order: 10, module: "Masters & Policy", section: "Metal" },
    { order: 11, module: "Masters & Policy", section: "Diamond Master" },
    { order: 11, module: "Masters & Policy", section: "Diamond" },
    { order: 12, module: "Masters & Policy", section: "ColorStone Master" },
    { order: 12, module: "Masters & Policy", section: "Colorstone Master" },
    { order: 12, module: "Masters & Policy", section: "Colorstone" },
    { order: 13, module: "Masters & Policy", section: "Finding Matser" },
    { order: 13, module: "Masters & Policy", section: "Finding Master" },
    { order: 13, module: "Masters & Policy", section: "Finding" },
    { order: 14, module: "Masters & Policy", section: "MISC Master" },
    { order: 14, module: "Masters & Policy", section: "MISC" },
    { order: 15, module: "Masters & Policy", section: "Item Master" },
    { order: 15, module: "Masters & Policy", section: "Item master and gst update" },
    { order: 16, module: "Masters & Policy", section: "Priority Master" },
    { order: 16, module: "Masters & Policy", section: " Priority Master" },
    { order: 17, module: "Masters & Policy", section: "Make Type Master" },
    { order: 18, module: "Masters & Policy", section: "QC Master" },
    { order: 19, module: "Masters & Policy", section: "Dust Resources" },
    { order: 20, module: "Masters & Policy", section: "MFG Department" },
    { order: 20, module: "Masters & Policy", section: "MFG Department " },
    { order: 21, module: "Masters & Policy", section: "Metal Purity" },
    { order: 21, module: "Masters & Policy", section: "Metal Purity " },
    { order: 22, module: "Masters & Policy", section: "Alteration Type" },
    { order: 23, module: "Masters & Policy", section: "Tax master" },
    { order: 24, module: "Masters & Policy", section: "Adavnce Price Policy" },
    { order: 25, module: "Masters & Policy", section: "Diamond Price Policy" },
    { order: 26, module: "Masters & Policy", section: "Labour Price Policy" },
    { order: 27, module: "Masters & Policy", section: "ColorStone Price Policy" },
    { order: 28, module: "Masters & Policy", section: "Setting Secondary Price Policy" },

    { order: 29, module: "PD", section: "Design Master" },

    { order: 30, module: "Sales CRM", section: "Album" },
    { order: 31, module: "Sales CRM", section: "Quote" },
    { order: 32, module: "Sales CRM", section: "Order / Sales Job Book" },
    { order: 32, module: "Sales CRM", section: "Order / Sales Job Book (B2B)" },
    { order: 33, module: "Sales CRM", section: "Retail Order" },
    { order: 33, module: "Sales CRM", section: "Retail Order (B2C)" },
    { order: 34, module: "Sales CRM", section: "Receive Repair" },

    { order: 35, module: "Books Keeping", section: "Material Purchase" },
    { order: 36, module: "Books Keeping", section: "Customer Receive" },

    { order: 37, module: "Inventory", section: "RM Stock" },

    { order: 38, module: "Vendor", section: "Vendor Outsource" },
    { order: 38, module: "Vendor", section: "Outsource" },
    { order: 39, module: "Vendor", section: "Issue Material" },

    { order: 40, module: "Books Keeping", section: "Stock Purchase" },

    { order: 41, module: "Vendor", section: "Return Material" },
    { order: 42, module: "Vendor", section: "Assign To Repair" },
    { order: 43, module: "Vendor", section: "Product Alteration" },
    { order: 44, module: "Vendor", section: "Product Alteration Receive" },

    { order: 45, module: "Inventory", section: "Stock Book" },
    { order: 46, module: "Inventory", section: "Tag Print" },
    { order: 47, module: "Inventory", section: "Stock Reconcile" },
    { order: 48, module: "Inventory", section: "RM Reconcile" },
    { order: 49, module: "Inventory", section: "Stock transfer" },
    { order: 50, module: "Inventory", section: "Splity Tranfer" },
    { order: 51, module: "Inventory", section: "Company to customer stock convert" },
    { order: 52, module: "Inventory", section: "Stock transfer(raw material)" },

    { order: 53, module: "Books Keeping", section: "Memo Issue" },
    { order: 54, module: "Books Keeping", section: "Memo Return" },
    { order: 55, module: "Books Keeping", section: "Jewellery Sale" },
    { order: 56, module: "Books Keeping", section: "Sale Return" },
    { order: 57, module: "Books Keeping", section: "Material Sale" },
    { order: 58, module: "Books Keeping", section: "Material Sale Return" },
    { order: 59, module: "Books Keeping", section: "Product Estimate" },
    { order: 60, module: "Books Keeping", section: "Retail Sale" },

    { order: 61, module: "Account", section: "Cash" },
    { order: 62, module: "Account", section: "Bank" },
    { order: 63, module: "Account", section: "Material settlement" },
    { order: 64, module: "Account", section: "Account Head" },

    { order: 65, module: "Manufacturing", section: "ETA Request Accept" },
    { order: 65, module: "Manufacturing", section: "ETA Req. Accpet " },
    { order: 66, module: "Manufacturing", section: "Engage Material" },
    { order: 66, module: "Manufacturing", section: "Engage Material " },
    { order: 67, module: "Manufacturing", section: "WAX Engage Material" },
    { order: 67, module: "Manufacturing", section: "WAX Engage Material " },
    { order: 68, module: "Manufacturing", section: "Casting Process & Casted Job" },
    { order: 68, module: "Manufacturing", section: "Casting Process and casted Job" },
    { order: 69, module: "Manufacturing", section: "Sprue Cutting" },
    { order: 70, module: "Manufacturing", section: "Sprue Grinding" },
    { order: 71, module: "Manufacturing", section: "Factory Outward" },
    { order: 71, module: "Manufacturing", section: "Factory Outward " },
    { order: 72, module: "Manufacturing", section: "Metal Loss Summary" },
    { order: 72, module: "Manufacturing", section: "Metal Loss Summary " },
    { order: 73, module: "Manufacturing", section: "WIP Report" },
    { order: 74, module: "Manufacturing", section: "WIP Reconcile" },
    { order: 75, module: "Manufacturing", section: "Dust collector - refining" },
    { order: 76, module: "Manufacturing", section: "Metal converstaion" },
    { order: 77, module: "Manufacturing", section: "Finding creation" },
    { order: 78, module: "Manufacturing", section: "Finding conversion" },
    { order: 79, module: "Manufacturing", section: "Stock melt - job melting - refining" },

    { order: 80, module: "FAQ", section: "Cache clear" },
    { order: 81, module: "FAQ", section: "Group management and it effect in album" },
    { order: 82, module: "FAQ", section: "Customer company name change" },
    { order: 83, module: "FAQ", section: "Action button in customer" },
    { order: 84, module: "FAQ", section: "Close job (Sales job book)" },
    { order: 85, module: "FAQ", section: "Design master -> Action button" },
    { order: 86, module: "FAQ", section: "Employee setting" },
    { order: 87, module: "FAQ", section: "Prefix changes" },
    { order: 88, module: "FAQ", section: "Stock book- Change diamond quality & color" },
    { order: 89, module: "FAQ", section: "Stock book- finding labour different" },
    { order: 90, module: "FAQ", section: "Policy verification" },
    { order: 91, module: "FAQ", section: "Loss recovery page" },
    { order: 92, module: "FAQ", section: "Loss recovery from Admin login" },
    { order: 93, module: "FAQ", section: "Close job restore" },
    { order: 94, module: "FAQ", section: "Quote close" },
    { order: 95, module: "FAQ", section: "Club job (mfg job book)" },
    { order: 96, module: "FAQ", section: "Branch Bill Inward" },
    { order: 97, module: "FAQ", section: "Cancel bill restore" },
    { order: 98, module: "FAQ", section: "Lab add" },
    { order: 99, module: "FAQ", section: "Huid and ceritficate add" },
];