/**
 * 📦 Auto-increment build version + generate version.json & version.js (no HTML injection)
 */

const fs = require("fs");
const path = require("path");

// Paths
const root = path.join(__dirname, "../");
const packagePath = path.join(root, "package.json");
const publicDir = path.join(root, "public");
const publicVersionPath = path.join(publicDir, "version.json");
const publicJsVersionPath = path.join(publicDir, "version.js");

(async () => {
  try {
    // --- 1️⃣ Read & increment version ---
    const packageJson = JSON.parse(fs.readFileSync(packagePath, "utf8"));
    const [major, minor, patch] = packageJson.version.split(".").map(Number);
    const newVersion = `${major}.${minor}.${patch + 1}`;
    packageJson.version = newVersion;
    fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2));
    console.log(`📦 Updated package.json → version ${newVersion}`);

    // --- 2️⃣ Generate version.json ---
    const versionData = {
      version: newVersion,
      buildTime: new Date().toISOString(),
    };
    fs.writeFileSync(publicVersionPath, JSON.stringify(versionData, null, 2), "utf8");
    console.log("✅ version.json generated:", versionData);

    // --- 3️⃣ Generate version.js ---
    const jsContent = `// Auto-generated by update-version.js
window.__APP_VERSION__ = "${newVersion}";
window.__BUILD_TIME__ = "${versionData.buildTime}";`;
    fs.writeFileSync(publicJsVersionPath, jsContent, "utf8");
    console.log("✅ version.js generated successfully");

    console.log("🎉 Version update process completed successfully!");
  } catch (err) {
    console.error("❌ Error during version update:", err.message);
    process.exit(1);
  }
})();




// /**
//  * 📦 Auto-increment build version + inject ?v=x.x.x into build/index.html
//  */

// const fs = require("fs");
// const path = require("path");

// // Paths
// const root = path.join(__dirname, "../");
// const packagePath = path.join(root, "package.json");
// const publicVersionPath = path.join(root, "public/version.json");
// const buildIndexPath = path.join(root, "build/index.html");

// (async () => {
//   try {
//     // --- 1️⃣ Read & increment version ---
//     const packageJson = JSON.parse(fs.readFileSync(packagePath, "utf8"));
//     const [major, minor, patch] = packageJson.version.split(".").map(Number);
//     const newVersion = `${major}.${minor}.${patch + 1}`;
//     packageJson.version = newVersion;
//     fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2));
//     console.log(`📦 Updated package.json → version ${newVersion}`);

//     // --- 2️⃣ Generate version.json ---
//     const versionData = {
//       version: newVersion,
//       buildTime: new Date().toISOString(),
//     };
//     fs.writeFileSync(publicVersionPath, JSON.stringify(versionData, null, 2), "utf8");
//     console.log("✅ version.json generated:", versionData);

//     // --- 3️⃣ Wait for build/index.html to exist ---
//     const waitForFile = async (file, retries = 10) => {
//       for (let i = 0; i < retries; i++) {
//         if (fs.existsSync(file)) return true;
//         console.log(`⏳ Waiting for build/index.html... (${i + 1}/${retries})`);
//         await new Promise((res) => setTimeout(res, 1000));
//       }
//       return false;
//     };

//     const exists = await waitForFile(buildIndexPath);
//     if (!exists) throw new Error("build/index.html not found after waiting");

//     // --- 4️⃣ Inject version number ---
//     let html = fs.readFileSync(buildIndexPath, "utf8");

//     // Remove any existing ?v= params first
//     html = html.replace(/\?v=\d+\.\d+\.\d+/g, "");

//     // Add ?v=version to all static assets (JS, CSS, favicon)
//     html = html.replace(
//       /(<script[^>]+src=["']\/static\/js\/[^"']+)(["'][^>]*>)/g,
//       `$1?v=${newVersion}$2`
//     );
//     html = html.replace(
//       /(<link[^>]+href=["']\/static\/css\/[^"']+)(["'][^>]*>)/g,
//       `$1?v=${newVersion}$2`
//     );
//     html = html.replace(
//       /(<link[^>]+href=["'][^"']*\.ico)(["'][^>]*>)/g,
//       `$1?v=${newVersion}$2`
//     );

//     fs.writeFileSync(buildIndexPath, html, "utf8");
//     console.log(`🧩 Injected version ?v=${newVersion} into build/index.html`);

//     console.log("🎉 Build version update completed successfully!");
//   } catch (err) {
//     console.error("❌ Error during version update:", err.message);
//     process.exit(1);
//   }
// })();
